name: Auto Merge Feature Branch to Development

on:
  pull_request:
    branches:
      - development

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # - name: Run Tests
      #   run: npm ci && npm test # Adjust this to match your project

      - name: Merge Feature Branch
        if: github.event.pull_request.merged == true
        run: |
          git config --global user.email "isanjit3@gmail.com"
          git config --global user.name "Auto Merge Feature Bot"
          git checkout development
          git merge ${{ github.head_ref }}
          git push origin development
